version: 2.1

build-template: &build-template
    docker:
        - image: w3tools/w3tools-node:16.17.0
    steps:
        - checkout
        - setup_remote_docker
        - run:
              name: Output Env Info
              command: node --version && yarn --version
        - run:
              name: Install Project Dependencies
              command: yarn
        - run:
              no_output_timeout: 10m
              name: Building ...
              command: yarn build
        - persist_to_workspace:
              root: '.'
              paths:
                  - '.'

upload-template: &upload-template
    docker:
        - image: w3tools/w3tools-awscli:latest
    steps:
        - setup_remote_docker
        - attach_workspace:
              at: '.'
        - run:
              name: Upload Artifacts
              command: aws s3 cp ./build s3://$BUCKET_NAME/ --acl bucket-owner-full-control --recursive --cache-control "public,max-age=600,s-maxage=3600"
        - run:
              name: Cloudfront Invalidation
              command: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'

jobs:
    # build
    build-main:
        <<: *build-template
    # upload
    upload-main:
        <<: *upload-template

workflows:
    version: 2.1
    w3tools_documentation:
        jobs:
            # docs.w3tools.app
            - approve-main:
                  type: approval
                  filters:
                      branches:
                          only: [main]
            - build-main:
                  requires:
                      - approve-main
            - upload-main:
                  context:
                      - cicd
                      - w3tools_documentation_main
                  requires:
                      - build-main
